my_velib_dbt_project:
  outputs:
    dev:
      dataset: example_datas
      job_execution_timeout_seconds: 300
      job_retries: 1
      keyfile: "{{ env_var('GOOGLE_APPLICATION_CREDENTIALS') }}" 
      location: EU
      method: service-account
      priority: interactive
      project: "{{ env_var('PROJECT_ID') }}"
      threads: 4
      type: bigquery
  target: dev
